PIL = "Pillow"
cv2 = "opencv-python"
yaml = "PyYAML"
bs4 = "beautifulsoup4"
sklearn = "scikit-learn"
Crypto = "pycryptodome"
Image = "Pillow"
dateutil = "python-dateutil"
MySQLdb = "mysqlclient"
mysql = "mysql-connector-python"
OpenGL = "PyOpenGL"
unittest = "unittest2"
skimage = "scikit-image"
psycopg2 = "psycopg2-binary"
